/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7qlxyyvtnba43kleov534jed54.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nmnhqw2szbb4bn5ksafgmmaawa",
    "aws_cognito_identity_pool_id": "us-east-1:97574941-341d-4b9c-b94a-5519cc4bf687",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HSVyQ1AwB",
    "aws_user_pools_web_client_id": "56gedggjqlha64a5s9sbvo8364",
    "oauth": {},
    "aws_user_files_s3_bucket": "tiktokd6167a089a4b487fa79d29fc8119f89161848-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
